### ISSUE TITLE
Supporting wrapping test assemblies for full MSTest parity

### ISSUE THREAD

**Issue by KevM** [fixie/fixie#108]
Conventions have hooks for Fixtures (classes) and Cases (methods) to be wrapped with a delegate. 

MSTest has a similar hook for their test assemblies.

```
[AssemblyInitialize]
Identifies a method to be called a single time upon before running any tests in a Test Assembly
[AssemblyCleanUp]
Identifies a method to be called a single time upon after running all tests in a Test Assembly
```

I believe simulating [AssemblyInitialize](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.assemblyinitializeattribute.aspx) would be possible with a Fixture wrap that conditionally does something the first time it is invoked. 

Sadly, I do not see how [AssemblyCleanup](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.assemblycleanupattribute.aspx) could get accomplished with the current seams in Fixie. Please let me know if I am incorrect.

I this feature seems like a good idea let me know and I'll see what I can do about a PR.

**Comment by plioi** [comment]
It *does* seem like a good idea, though I agree that in order to deal with both Init and Cleanup, we'd need something new baked into the main loop, rather than the Convention's hooks for test class and test case bits.  There can be any number of conventions in a single assembly, for instance.

**Comment by KevM** [comment]
Great. I will look into this. Not making any promises for the short term. Long term I have a bunch of MSTest projects I'd like to migrate onto Fixie and one of them has a really horrible `[AssemblyCleanUp]` method.

**Comment by Suremaker** [comment]
Hello @plioi , I wanted to check if there is anything going on regarding assembly level wrappers?

I see there is a concept of listeners implemented (https://github.com/fixie/fixie/tree/master/src/Fixie/Execution/Listeners) but I do not believe there is a way to specify custom ones and wire to fixie...

**Comment by plioi** [comment]
Listeners tend to be more a matter of how results get reported (xml, team city, plain console, appveyor...).

If you see the conventions under the Samples project, notably the "Skipped" example since that's a nontrivial one, you'll see the new 2.x way of defining custom lifecycle behavior (it fixes a lot of subtly-broken concepts in 1.x at the cost of being a little more explicit).  I've been tinkering with the idea of offering another overload of Execute. The Execute you see in the sample is, as the parameters imply, called once for each test class.  So, that lets you get the class-level wrapping you're familiar with.  If an overload of Execute were also available with different args, that may let us say "here's how to execute the convention for the whole assembly" if one wanted to do some work before or after the *existing* Execute(...) loop. Thoughts?

**Comment by KevM** [comment]
If it wasn't obvious I abandoned my attempt at this. We used regex to migrate away from MSTest.

**Comment by plioi** [comment]
No worries. I changed the world in the meantime :). It's still a good hook to have, so I'd like to find a way.

**Comment by plioi** [comment]
Fixie 2 has finally be released. Check up on the latest docs to get aquainted with the new Discovery and Execution types, which you subclass to customize the discovery and execution phases. What's not documented yet is that your implementation of Discovery and Execution, can optionally be IDisposable.

If they need to do any heavy lifting at the start and end of the assembly run, they can do that work in the constructor and Dispose() method.

Since this would most likely be done for an execution-phase concern, I'd recommend splitting such a convention into two separate classes, one implementing Discovery (with no interesting constructor/dispose) and one implementing Execution (with the intended heavy lifting). Otherwise, the heavy work would take place even in a discovery-only run such as when Test Explorer determines the tree of tests to show.
