### ISSUE TITLE
Use case's Fixture in Skip predicate

### ISSUE THREAD

**Issue by eddiegroves** [fixie/fixie#109]
I'm adding in a convention to skip ordered test cases if a previous test case in the class has failed. Here's what I'm trying to do:

```
CaseExecution.Skip(SkipIfPreviousTestFailed, _ => "A previous test case has failed");

...

private static bool SkipIfPreviousTestFailed(Case @case)
{
    return @case.Method.Has<OrderAttribute>() && @case.Fixture.Cases.Any(c => c.Exceptions.Count > 0);
}
```

However `Fixture` is null, so this won't work. Is using `Fixture` inside the skip predicate not supported?

Cheers!

**Comment by plioi** [comment]
The short version: your use case is about an execution-time decision to stop running subsequent test cases, while Skipping is a pre-execution decision.  I think a different customization hook will fill your needs.

**Details**

Fixture, here, is the instance of the test class.  Test skipping happens before test cases are executed ( https://github.com/fixie/fixie/blob/master/src/Fixie/Internal/ClassRunner.cs#L64 ), and therefore there is no test class instance yet.  If it weren't null, it'd be ambiguous *which* instance we'd want to be there.

Your use case suggests adding support for the similar concept of an *Ignored* test, in which a test case is *not* skipped and *does* run, but elects to bail out early and have its result left out. With a skipped test, it's never even run.  We can come very close to such an *Ignored* feature with Fixie as-is, though...

**What to Try**

Instead of using the Skip feature, try to affect the behavior of the running test cases with the "Wrap" option.  Try to use CaseExecution to `.Wrap(..)` the execution of the test case, only proceeding to the normal execution when the Fixture (which should exist by then) has no failed tests yet.  The behavior will call next() if it should run, and should return without calling next() if it should not run.  This may not fit your wishes, but in this situation it'll count as a Passing test case.  I'd like to eventually support Ignored tests, too, which would make your customization even nicer.

Here's some untested code that is worth trying:

```cs
CaseExecution
    .Wrap<SkipIfPreviousTestFailed>();
```

```cs
public class SkipIfPreviousTestFailed : CaseBehavior
{
    public void Execute(Case @case, Action next)
    {
        bool anyPreviousTestFailed =
            @case.Method.Has<OrderAttribute>() && @case.Fixture.Cases.Any(c => c.Exceptions.Count > 0)
        
        if (!anyPreviousTestFailed)
            next(); //Continue to run the test case.
    }
}
```

**Comment by eddiegroves** [comment]
Thanks Patrick, I had a hunch that might be the case. 

Using `CaseExecution.Wrap` is a suitable alternative - looks like I could let the ignored tests pass or fail them with `@case.Fail(new Exception("A previous test case has failed"))`.

As an aside I'd like to praise the design of Fixie - it's wonderful how it encourages me to build my own test framework :+1:
