### ISSUE TITLE
Skip and TFS/VSO Build - FAILS

### ISSUE THREAD

**Issue by DynConcepts** [fixie/fixie#122]
Using the Skip approach outlined elsewhere, all tests are still being discovered and executed (and in this case failing).

When using the Test Runner plug-in, what is the proper way to mimic the [Ignore] attribute of MsTest????

**Comment by plioi** [comment]
I'm happy to help diagnose this issue, but I'll need more information. Can you copy/paste your Convention and a sample test that is being mishandled?

**Comment by DynConcepts** [comment]
Simple Attribute...

        [Skip(Reason = "Find out why this is failing only some of the time")]
        public void SomeTest(TestContextFixture fixture, ...) {}

The same code when submitted directly to Fixie (not using VSO / VsTest) appears to properly skip)

**Comment by DynConcepts** [comment]
Confirmed...within VS they are skipped, when run from VSO they fail...

![fixie](https://cloud.githubusercontent.com/assets/9969889/10435217/86830066-70ec-11e5-975c-5c0a8816e3f2.png)

**Comment by plioi** [comment]
1. Can we see your convention class?
2. Is there any chance another test framework is also present, like xunit?
3. When I run from VS can go to the Output pane and select Tests for some useful logging. Can you do the same for VSO? That might confirm whether it is really fixie running in the failure case

**Comment by plioi** [comment]
MS has never put much effort into the Test Explorer feature, especially for non-MSTest frameworks, and I suspect we're seeing a similar lack of attention to detail from VSO.

Your sample code and screenshot confirm a few things:

1. Fixie is correctly identifying your skipped tests as not being run.
2. Fixie is correctly setting a useful message explaining the reason for not being run.
3. VSO is probably mistakenly considering the message string to mean failure, even though Fixie sets the outcome to NotRun.

Item 3 above is an educated guess.  Let's prove it one way or the other: change your convention so that the Skip Reason string is always null, and see if VSO starts to pay attention.  If so, I'll consider publishing a change to the VS support in which skip reasons will be left out of the Error Message field and put them somewhere else instead, but I can't do that until I get confirmation that it's truly the culprit.

If you can post a similar screenshot of the results after you make the Skip Reason always null, then I'll look into publishing a workaround.

**Comment by DynConcepts** [comment]
Patrick, can we take this private?     David.corbin@dynconcepts.com<mailto:David.corbin@dynconcepts.com>

**Comment by plioi** [comment]
Fixed in 1.0.0.33 https://github.com/fixie/fixie/releases/tag/v1.0.0.33
