### ISSUE TITLE
Before/After Entire Test Suite

### ISSUE THREAD

**Issue by JoeGannon** [fixie/fixie#123]
I've been looking in the docs and online but haven't been able to turn up anything. Is it possible to execute code one time before/after the entire suite of test cases? I'm using selenium for UI testing and would like to open/close the web driver once per test suite execution since it is an expensive operation. Maybe it's even possible to wrap multiple test classes around a single fixture?

**Comment by plioi** [comment]
Currently there are hooks for the start and end of a test case, the start and end of a test class instance, and the start and end of a test class.  Others have expressed an interest in hooks for the start/end of a Convention or of the whole test Assembly.

**Comment by plioi** [comment]
If you are resolving your test class instances via an IoC container, could that help give you the control you need over the web driver?

**Comment by CSharpest** [comment]
If the container could tell me  "All your UI tests are finished running" then yea this would work. I'd just close the driver at that point. I'll look into possible implementations.

**Comment by cquillen** [comment]
Did you ever resolve how to shut down webdriver?

**Comment by giggio** [comment]
This is really important for any test that has a heavy setup or teardown. One of the reasons I'm running away from xUnit.

**Comment by JoeGannon** [comment]
@cquillen I wasn't able to. It required some manual intervention at times... which probably could've been automated. We had stopped using selenium shortly after so I hadn't put much work into it.

**Comment by Suremaker** [comment]
Hello @plioi ,

I am developing [LightBDD](https://github.com/LightBDD/LightBDD) framework that runs on top of test frameworks such as nunit/xunit/mstest offering ability to write and run BDD-like tests. 
I have found fixie framework very appealing and started looking on possibility to extend the LightBDD integration capabilities to support fixie as well.

In order to properly integrate my project with test framework I need however an ability to execute some initialization code before any test is performed as well as cleanup code after all tests are finished.
I have noticed that this is the functionality that fixie does not offer at this moment (it is addressed here and similar request has been made in #108) so I wanted to ask if there is any chance to get this issue implemented any time soon?

Thanks!

**Comment by plioi** [comment]
Thanks for your interest in the project!

The hooks you're asking for make a lot of sense.  My primary concerns right now are the Fixie 2.x release, which focuses on .NET Core support. It will also probably include some significant changes to the existing hooks, and may make it easier to add the hooks you're asking for. The .NET Core support is about 95% done and the changes to the hooks are in an experimental phase I hope to work through in a couple weeks.

I'm going to close this Issue, and recommend that you follow #108 in the next few weeks.
