### ISSUE TITLE
AppVeyorListener and console output

### ISSUE THREAD

**Issue by potz** [fixie/fixie#138]
I noticed that when using the AppVeyor listener, tests are correctly posted to the API but there is no console output while they are running, just the appveyor api calls. Is that by design or am I missing some option that must be set to also have console output?

**Comment by plioi** [comment]
You're right.  In the 1.x code (master), there is a limitation in the way events are handled, so that there is only one "Listener" enabled at any time.  The AppVeyorListener is enabled when running under AppVeyor, with the unfortunate side effect that the ConsoleListener is turned off.  One possibility would be to implement a decorator pattern in the 1.x code so that both could be bottled up into "one" listener.  This is not going to be a problem in the 2.x code, in which the behind-the-scenes messaging infrastructure is much more robust.

**Comment by potz** [comment]
Got it, not a big problem anyway.

Congrats on the extremely elegant test framework btw, a joy to use.

**Comment by plioi** [comment]
Thanks!
