### ISSUE TITLE
Are custom options supported for the .Net Core console runner?

### ISSUE THREAD

**Issue by trevorchunestudy** [fixie/fixie#160]
## Steps to Reproduce
Using 'ModelWithProperties' test class from 'experimental...' branch and examples from wiki, setup a test fixture to allow console options.

## Expected Behavior
Console runner to accept options.

## Actual Behavior
The argument '--foo' was unexpected and will be ignored.
The argument 'bar' was unexpected and will be ignored.

Appears to be tests in this experimental branch that support console options.  Not sure what I am doing wrong.

**Comment by plioi** [comment]
The command line argument handling of dotnet test has been problematic and there may have been breaking changes from the MS folks between this working for me and it not working for you.  Let's first make sure we're talking about the same scenario before we can make sense of your error message.

What version of Fixie are you using?

What is output when you execute `dotnet --version` from the same folder?

What is your exact command line when you get the error messages described under "Actual Behavior"?

**Comment by plioi** [comment]
https://github.com/fixie/fixie/blob/experimental-dotnet-core-preview-tooling/src/Fixie.Runner/Program.cs#L21  As seen here, the first thing we do once MS hands the command over to us is separate arguments into two categories, using the special argument "--" to separate them.  You may wan to put a "--" before your custom arguments. For instance, `dotnet test .\src\MyTestProjectFolder --configuration Debug -- --foo bar`

**Comment by trevorchunestudy** [comment]
Admittedly, I'm still trying to figure out the correct way to use this tool. My project is .net core based but it specfically references .net 461.  I am using the alpha-0001 version and running the dotnet-test-fixie console app.  The console app runs all of my tests perfectly.  It only has issues when I add CLI arguments.
```
>dotnet-test-fixie.exe ..\MyTest.dll --foo bar
The argument '-foo' was unexepcted and will be ignored.
etc.
100 of 100 Tests ran successfully
```
I'm probably using this the wrong way however, I really appreciate your help and find this project very useful.

**Comment by plioi** [comment]
Aha!  One big difference introduced by .NET Core is that there is a new command line tool, dotnet.exe, that we can use as the entry point for compiling, running tests, etc.

So, try this:

`dotnet test YourTestProjectFolderName -- --foo bar`

If you don't have dotnet.exe then that's the first thing you'll need to install. Notice that you specify the folder name that contains your poject files, rather than a dll.  Notice the special "--" argument that Fixie uses to make sense of arguments.  The args *before* -- will be args for dotnet exe itself, and the args after -- will be custom convention stuff.

Behind the scenes, dotnet.exe will find dotnet-tes-fixie.exe and invoke it itself, with a handful of special args you and I never really *see* in addition to the args you type in yourself.

In order for dotnet.exe to recognize that Fixie is a test framework and that you are using Fixie, your test project's project.json will need to say so:

```json
{
  "testRunner": "fixie",
  "dependencies": {
    "Some.Project.In.Your.Solution": { "target": "project" },
    "Fixie": "2.0.0-alpha-0001",
    "Should": "1.1.20"
  },
  "frameworks": {
    "net461": {}
  }
}
```

**Comment by trevorchunestudy** [comment]
Thats it! You nailed it! Thanks Patrick. Works perfectly.  Fixie is making my build pipeline so much more robust.  I know you and Jimmy are very busy over there at Headspring but I really appreciate the time you take on your blog posts, libraries, and help.
