### ISSUE TITLE
What is the best practice to build framework on top of Fixie?

### ISSUE THREAD

**Issue by Suremaker** [fixie/fixie#186]
Hello,
I was looking on how I can integrate my library to run on top of Fixie and came to the point where it works well if I create two custom classes in my framework `MyFramework.csproj`:
* `public class MyFrameworkDiscovery: Discovery { /* ... */ }`
* `public class MyFrameworkExecution: Execution, IDisposable { /* ... */ }`

What I observed however, that if I want to use my framework in the project `A.csproj`, I have to introduce another 2 classes deriving from the framework ones, like:
* `class WithMyFrameworkDiscovery: MyFrameworkDiscovery { }`
* `class WithMyFrameworkExecution: MyFrameworkExecution { }`

I wonder if this is the valid way of reusing my framework conventions in other projects or if there is a way to make a requirement of adding only one class in the target library (or possible none and making it autodiscovered)?

The reason why I have separate classes for discovery and execution is the suggestion from: #108 (as I need to implement `IDisposable` on execution convention).

As an alternative I wonder if future versions of Fixie could have `Discovery` class extended with `Executors` property that will allow to configure executors like parameters are done, ie:
`Executors.Add<MyCustomExecutor>();` or something similar ? - with this approach it would be possible to define all conventions/configurations in one place and minimise number of classes that have to be declared in test projects.

**Comment by plioi** [comment]
Thanks for showing an interest in the project and pushing against its boundaries! 2.0 is a huge shift from 1.0 so I'm sure folks will be uncovering a few gaps as they apply it to the real world.

I'm open to extending the API to allow for reuse of these Discovery and Execution classes, but I really need to dig further into peoples' use cases before I can do so in a way I'd be comfortable with. We've been using Fixie at my employer since its inception a few years back and we have always, without exception, regretted any convention reuse/inheritance.

Part of why we've regretted it is that it leaves a developer joining the team far less likely to know how tests are to be written in the project. With an unambiguous class (or in the case of separate Discovery/Execution, 2 classes) where you can go and just read top to bottom how tests behave *here*, there's little room for surprises or complexity creep.

So, the things that you're inheriting from one assembly to another... 

1. For the Discovery parts, could it be some set of extension methods on the `Classes...` and `Methods...` properties?
2. For the Execution parts, could there be something that your Execute(...) methods *call out to* that is shared?

Another direction to come at the question (so I can see the whole picture and find common threads with others who ask for similar features) is, "If all your test projects in the solution run their tests the same way, why are they in different test projects to begin with?"

**Comment by dude0001** [comment]
Has there been any more thought about this? Is it possible to reuse conventions in Fixie 2 without deriving from conventions defined in a shared library?

**Comment by plioi** [comment]
Fixie version 3 was just released, and it has a simple convention reuse model, now. See the updated documentation and the way that a test project's `ITestProject` hook can register any number of `IDiscovery`/`IExecution` pairs defined in any assembly.

Thanks for the feedback. Apologies that it took so long, but this heavily influenced the work that went into version 3.
