### ISSUE TITLE
How can I plugin a DI container to create test method parameters?

### ISSUE THREAD

**Issue by Rookian** [fixie/fixie#191]
I want Fixie to create my test method parameters by using SimpleInjector as a DI container.
To make sure that each test is isolated and gets fresh dependencies, first I register them in a scope and secondly I create a scope `AsyncScopedLifestyle.BeginScope(container)`. 

The problem is that `InputParameterSource.GetParameters` is called before I opened the scope and SimpleInjector is throwing an exception.
```
public class DependencyInjectionBasedExecution : Execution
{
    public void Execute(TestClass testClass)
    {
        var container = Convention.Container;
        testClass.RunCases(@case =>
        {
            using (AsyncScopedLifestyle.BeginScope(container))
            {
                var instance = container.GetInstance(testClass.Type);
                @case.Execute(instance);
                container.Dispose();
                instance.Dispose();
            }
        });
    }
}
```

```
public class Convention : Discovery
{
    public static Container Container { get; private set; }

    public Convention()
    {
        Container = BootContainer();
        Classes.Where(x => x.Name.EndsWith("Tests"));
        Parameters.Add(new InputParameterSource(Container));
    }
}
```

```
public class InputParameterSource : ParameterSource
{
    private readonly Container _container;

    public InputParameterSource(Container container)
    {
        _container = container;
    }

    public IEnumerable<object[]> GetParameters(MethodInfo method)
    {
        var parameters = method.GetParameters();
        var objects = new object[parameters.Length];

        for (var index = 0; index < parameters.Length; index++)
        {
            var parameterInfo = parameters[index];
            objects[index] = _container.GetInstance(parameterInfo.ParameterType);
        }

        yield return objects;
    }
}
```

Instead of calling `Case.Execute` and using `InputParameterSource` I could write my "own" `Case.Execute` method.

Should I implement my own `Case.Execute` method or am I doing something wrong?

**Comment by plioi** [comment]
We've attempted to call GetParameters as late as possible, though it seems you've uncovered a chicken/egg problem.

See https://github.com/fixie/fixie/blob/master/src/Fixie/Internal/ClassRunner.cs#L54-L65 where we lazily yield one Case object at a time, calling your caseLifecycle against each one (caseLifecycle being the lambda you are passing to RunCases).

Since a Case is constructed with the parameters, the Case exists before arriving in your lambda, so it's too late.

Your goal makes sense, but I'm not sure I see a way out of the chicken/egg problem. We want to evaluate the input parameters to a case before arriving in your customization lambda (otherwise we wouldn't know how many times to invoke your lambda for a given test method, for instance), but you're naturally wanting to evaluate them yourself after the fact.

*Maybe* it's worth trying to do the scope begin/end inside the parameter source, though we're bumping up against my understanding of SimpleInjector, so maybe that's invalid.

But...

I used to recommend the idea of an "ambient" scoped container wrapping a whole test method invocation, but I've since come to regret it. Nowadays, I recommend a similar concept where test helper methods (often brought in with `using static ...`) operate under their own scoped container individually. 

Image a test method for a feature that inserts a record. When the app is running, you might have some web-request-scoped container from which you resolve and Entity Framework DbContext as the unit of work. You might then have a test that sets up an initial state, provokes the INSERT work, and then asserts on the database contents. With a container scope around the whole test, we'd actually be *diverging* from the production scenario. I'd rather a test helper method ("Scope(...)") which does container work on a smaller scale. My Scope helper likewise establishes a transaction just like the production web request would have.

public void TestTheThing()
{
    Scope(() => { /* do setup steps */ });

   Scope(() => { /* exercise the SUT */ });

   Scope(() => { /* verify the effects of the SUT */  });
}

I'm oversimplifying a bit. I usually add less verbose helpers for the most common setup/work/assertion steps, but they ultimately call down into a transaction-with-scoped-container helper. The point is, if we had just one scoped container around the whole test, it would *definitely* not reflect the container usage of the real production system. Our DbContext for instance would be heavily polluted by the setup, and our assertions might be fooling us due to unintended caching in that extra-long-lived DbContext.

**Comment by Rookian** [comment]
> We want to evaluate the input parameters to a case before arriving in your customization lambda (otherwise we wouldn't know how many times to invoke your lambda for a given test method, for instance), but you're naturally wanting to evaluate them yourself after the fact.

I think a `ParameterSource `could just return `IEnmuerable<Parameter[]>` and after that you could provide an additional interface `ParameterProviderSource`, who runs right before the test case is invoked. 

ParameterSource is responsible for just getting some meta information (type, name, instance, ...) whereas with a `ParameterProviderSource `you can override the instance.

**Comment by Rookian** [comment]
> Maybe it's worth trying to do the scope begin/end inside the parameter source, though we're bumping up against my understanding of SimpleInjector, so maybe that's invalid.

https://simpleinjector.readthedocs.io/en/latest/decisions.html?highlight=Scope#dont-allow-resolving-outside-an-active-scope

I think you can only start the scope inside a `ParameterSource` and end it after the test case executed. I will try this.

**Comment by Rookian** [comment]
My current "solution":

```
public class TestConvention : Discovery, Execution
{
    private Container Container { get; set; }

    /// <summary>
    /// This is not thread safe, but Fixie tests can't run in parallel
    /// </summary>
    private Scope CurrentScope { get; set; }

    public TestConvention()
    {
        Classes.Where(x => x.Name.EndsWith("Tests"));

        Methods.Shuffle();
        
        Container BeginScope()
        {
            Container = BootContainer();
            CurrentScope = AsyncScopedLifestyle.BeginScope(Container);
            return Container;
        }

        Parameters.Add(new InputParameterSource(BeginScope));
    }

    public void Execute(TestClass testClass)
    {
        testClass.RunCases(@case =>
        {
            var container = Container;
            object instance = null;
            try
            {
                instance = container.GetInstance(testClass.Type);
                InitializeDbs(container).Wait();
                @case.Execute(instance);
            }
            finally
            {
                CurrentScope.Dispose();
                container.Dispose();
                instance?.Dispose();
            }
        });
    }
}

public class InputParameterSource : ParameterSource
{
    private readonly Func<Container> _beginScope;

    public InputParameterSource(Func<Container> beginScope)
    {
        _beginScope = beginScope;
    }

    public IEnumerable<object[]> GetParameters(MethodInfo method)
    {
        var container = _beginScope();

        var parameters = method.GetParameters();
        var objects = new object[parameters.Length];

        for (var index = 0; index < parameters.Length; index++)
        {
            var parameterInfo = parameters[index];
            objects[index] = container.GetInstance(parameterInfo.ParameterType);
        }

        yield return objects;
    }
}

```

**Comment by webseb** [comment]
I just asked a question in a [related issue](https://github.com/fixie/fixie/issues/96) but this one fits my problem even better: Is there a way to let a scoped/nested container create parameters for test methods or does the separation in a Discovery and an Execution stage prevent this?

**Comment by plioi** [comment]
It's worth experimenting with to know for sure. I don't have a solid answer at the moment, and unfortunately I probably won't get to investigate possible test class discovery/lifecycle adjustments until the 3.x timeframe (guessing that'll coincide with .NET 5).

However, I strongly reiterate my warning above when I discourage "ambient" containers around a test method invocation. We have regretted it completely, every single time we think it's a good idea, as when we do so we are actively lying to ourselves about the realism of the test vs the nature of the production system.

I go on about the alternative advised patterns more here: https://github.com/fixie/fixie.demo/blob/master/README.md

**Comment by plioi** [comment]
This and related issues definitely revealed the design flaws around paramterization. It had been a mistake to treat paramterization as an aspect of the "discovery" phase when it better fits in the "execution" phase. That led to painful attempts to work around the limitation, and a lot of dead ends.

Thankfully this discussion heavily influenced the new API in version 3 which just released. I believe we now have much more direct control over parameterization in a natural context, where you can handle your parameterization scheme using plain old C# in the execution phase.

Closing this in light of the new API in version 3.
