### ISSUE TITLE
Custom listener - reporter

### ISSUE THREAD

**Issue by skyflyer** [fixie/fixie#223]
Is it possible to add (or replace) listeners? I see that the `Entrypoint` has a configured a fixed list of default listeners (`DefaultExecutionListeners`) and I would like to add a new one (ideally replace others).

**Comment by plioi** [comment]
This is a good idea, but not currently supported. I've been considering exposing this as a feature in Fixie 3, which is in the middle of development.

One risk is that as soon as this is public, the API involved needs to become highly stable so we don't break reporters with each release.

So that I can be sure to have a real world use case in mind, what would your reporter do, and which existing DefultExecutionListeners would you then want to suppress?

**Comment by skyflyer** [comment]
Let me first thank you for your efforts in developing and maintaining Fixie!

I'm starting development of a custom integration-test runner, that I need to customise for customer's needs. So I'm evaluating different options, among which Fixie is one.

The requirements are:

* custom test execution (with setup and teardown) (✔︎)
* custom test discovery and ordering (✔︎)
* custom reporting with additional test artifacts

The last one is actually tricky: I need to execute a test and have the ability to send additional information to the reporter (such as a "screenshot" of a failed test).

Thinking about this... I guess that would be quite a stretch to adapt Fixie to cater to my needs and I might end up rolling my own, since it is not that big of a deal anyhow (and I'm targeting only .NET Core).

What are your thoughts on this matter?

**Comment by plioi** [comment]
The open-ended nature of your description for th report does make me wonder whether the Listener pattern here would be good enough. I suggest you take a scan through the existing folder of *Listener classes to see what kinds of informatin they have available to them and what kinds of things they do as output.

Your screenshot example for instance might not fit here, mostly due to _timing_. The Handle(...) methods are called *after* things like a test completion takes place. Imagine a test is scripting out actions against a live browser window... the window would probably arleady be closed by the time the reporter was asked to record a test failure, and that point you'd really only have the test name/exception to work with.

To capture a screenshot, that might be more realistic in your subclass of Execution, which is really what will still be running while the (for example) browser window is still open and worthy of a screenshot.

**Comment by skyflyer** [comment]
You're probably right that I will need much more customisation than another listener for reporting purposes.

I'll see what I come up with and reopen this with a concrete use-case if it will make sense.

Thank you very much for your input!

/close
