### ISSUE TITLE
Enable `RollForward = Major` to run on later .NET Core versions

### ISSUE THREAD

**Issue by nil4** [fixie/fixie#246]
Fixie.Console 2.2.1 targets `netcoreapp3.1`:

https://github.com/fixie/fixie/blob/410663d60315fa5a47583468ea9e3dcec1076f1f/src/Fixie.Console/Fixie.Console.csproj#L5 

However, if the only .NET Core SDK installed is a later one (e.g. 5.0), then running tests in a project which references it like this fails:

```xml
    <DotNetCliToolReference Include="Fixie.Console" Version="2.2.1" />
```

(Note: this might be caused by a Fixie.Console transitive dependency)

## Steps to Reproduce

This commit https://github.com/nil4/dotnet-transform-xdt/commit/9cab0ad48284c0d53256be33b3b83542aeda8c67 updates the SDK to 5.0. The GitHub actions build failed with the following message:

```
dotnet fixie --configuration Release --report test-results.xml
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      5.0.0 at [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
```
 
This reproduces locally with this `dotnet --info` output:

<details>
<summary>dotnet --info</summary>
<pre><code>>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]</code></pre>
</details>

## Expected Behavior

`dotnet fixie` works when only a later .NET SDK (e.g. 5.0) is installed.

## Actual Behavior

`dotnet fixie` fails when 'Microsoft.NETCore.App', version '2.0.0' is not available.

## More information

In the local NuGet cache folder, I updated `dotnet-fixie.runtimeconfig.json` with the following:

```diff
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
+   "rollForward": "Major",
      "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    }
  }
}
```

This runtime option is documented here: https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#runtimesdk 

With this change, the issue appears resolved. The output is below, for reference:

<details>
<pre><code>dotnet fixie --configuration Release --report test-results.xml
Building dotnet-xdt.tests...
  dotnet-xdt -> D:\projects\dotnet-xdt\dotnet-xdt\bin\Release\net461\dotnet-xdt.exe
  dotnet-xdt -> D:\projects\dotnet-xdt\dotnet-xdt\bin\Release\netcoreapp2.1\dotnet-xdt.dll
  dotnet-xdt.tests -> D:\projects\dotnet-xdt\dotnet-xdt.tests\bin\Release\netcoreapp3.1\dotnet-xdt.tests.dll
  dotnet-xdt.tests -> D:\projects\dotnet-xdt\dotnet-xdt.tests\bin\Release\net48\dotnet-xdt.tests.dll
  dotnet-xdt.tests -> D:\projects\dotnet-xdt\dotnet-xdt.tests\bin\Release\net5.0\dotnet-xdt.tests.dll
Running dotnet-xdt.tests (net5.0)

5 passed, took 0.15 seconds

Running dotnet-xdt.tests (netcoreapp3.1)

5 passed, took 0.15 seconds

Running dotnet-xdt.tests (net48)

5 passed, took 0.15 seconds
</code></pre>
</details>

Would you be possible to add the `<RollForward>Major</RollForward>` to the Fixie.Console project? 
See https://github.com/nil4/dotnet-transform-xdt/issues/42 for a change that helped a similar use case.

**Comment by plioi** [comment]
https://github.com/dotnet/sdk/issues/3115 DotNetCliToolReference tools are a deprecated concept intended only to work on .NET Core 2.2 or below. If your suggestion would work, it'd definitely be outside the intended support path.

Rather, we are close to releasing Fixie v3 which will provide the modern alternative, a so called "local tool". I expect a beta release in the next week.

**Comment by nil4** [comment]
As far as I understand it, the restriction described in https://github.com/dotnet/sdk/issues/3115 is only that CLI tools must *target* .NET Core 2.2 or lower. 

> DotNetCliToolReference tools will be restricted to ***targeting*** .NET Core 2.2 and below. DotNetCliToolReference tools can be used in projects targeting .NET Core 3.0, but the tools themselves should target .NET Core 2.2 or below.

I found two comments https://github.com/dotnet/sdk/issues/3115#issuecomment-482340558 and https://github.com/dotnet/sdk/issues/3115#issuecomment-545054281 particularly relevant. 

There is no restriction that tools cannot *run* on later versions; they just don't do that *by default*. But it is possible to opt-in using `<RollForward>Major</RollForward>`. This is documented at https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-runtime-roll-forward and it works as documented. 

Hopefully https://github.com/fixie/fixie/pull/247 shows what this looks like. It helps to build Fixie and run its tests with only .NET 5.0 SDK available. 

This is not a blocker for my use case on `dotnet-xdt`. I verified that the tests pass locally on .NET 5.0 SDK. 
It would be nice to be able to keep using the CLI tool (which is automatically restored during build) if possible. 

But if you feel that the change suggested is not supported, or not beneficial to Fixie's roadmap, please feel free to close this issue and the PR.

**Comment by plioi** [comment]
As you've probably seen, I merged #247 for the v3 line of development.

Your research and elaboration above is informative, and I wish I had connected those dots myself about a year ago when my teammates noted that they had to install 2 SDKs in their CI systems to get by as a workaround. I've tried to pride myself on Fixie's emphasis on "developer ergonomics", and telling them to install 2 SDKs "because MS got weird" was not exactly a consistent take :).

The fact you say you're unblocked, though, suggests you might have already noted you can just run your test project build output as-a-console-application for the same effect, but I just wanted to say so explicitly here in case that "unadvertised feature" wasn't on your radar yet.

With the overall push from MS to have folks move away from .NET Framework and away from .NET Core 2.x towards .NET Core 3.1 (for LTS) and .NET 5 (for more adventurous souls), and with the corresponding pressure to have everyone use Local tools instead of DotNetCliToolReference from now on as described in dotnet/sdk#3115, I'm going to stick with the roadmap decision that Fixie v3 will use the Local Tools style command line experience moving forward.

One of the big challenges with the v2 line of development that led to v3-in-progress was the growing effort involved in developing, building, and testing v2 changes against the "wide" surface area of .NET Framework, .NET Core 2.x and .NET Core 3.x consumers. The packaging and runtime concerns for each of those were surprisingly different and ever-changing with each VS minor update. Integrating with Test Explorer across that wide surface area invovled some very surprising and very atypical constraints and pain points. So, I admit I don't have a lot of energy in developing changes against the v2 line *in general*. Specifically in this case, I'd entertain a PR that branched off of tag 2.2.1 and merges back to `master` (which I'm surprised to see is still present, but at the right location for a hypothetical 2.2.2 target) rather than `main`, though with the 2 available workarounds (install both SDKs, or just invoke the test project assembly directly) it may not be worthwhile.

**Comment by plioi** [comment]
@nil4 Apologies for the delay. Things got bonkers at work. I've merged your 2.x fix and have released both packages: Fixie and Fixie.Console version 2.2.2 contains your fix.

Please confirm that the behavior matches your expectation, at your convenience, and feel free to close this issue at that time.

**Comment by nil4** [comment]
@plioi no worries at all, and much appreciated! 

I've been quite busy as well and in the meantime I have archived the `dotnet-transform-xdt` repo. Will bring it back shortly to add this and a couple of deterministic build fixes before archiving it for good. 

I will close the issue once I have confirmed the build, hopefully within the next couple of days.

**Comment by nil4** [comment]
@plioi thank you very much once again! I confirm that Fixie 2.2.2 works as intended on newer SDK versions.

**Comment by plioi** [comment]
Excellent, thanks.
