### ISSUE TITLE
Profiler fails to show any of my code when running a fixie test.

### ISSUE THREAD

**Issue by StevenTCramer** [fixie/fixie#254]
## Steps to Reproduce
Run the profiler while running fixie and I don't ess any of my code.
![image](https://user-images.githubusercontent.com/357219/118379302-98d22c80-b603-11eb-8972-a669129a56bb.png)

## Expected Behavior
I run same test using XUnit and I can my code.

## Actual Behavior
I just see fixe and coreclr in the list

**Comment by plioi** [comment]
I'm unfamiliar with the feature you're talking about, and I'm not seeing anything profiler-related in the Test Explorer UI, so I'd need some background on what you're invoking when this does work for xunit and what similar thing you're doing when it fails to give useful results for fixie.

If this is comparable to setting up a debugger attachment, it might help to know about how fixie works at the Process level. I'm assuming v2 here:

* `dotnet fixie` is "dumb" and simply finds your test project build output and invokes it as a console application. If you're profiling the executable that implements `dotnet fixie` itself, for instance, you won't see much of interest there; you'd rather care about the processes it kicks off for you.
* The Test Explorer plugin is a process kicked off by VsTest, and it works by similarly starting up the test project assembly as a console application, this time in a mode where both processes know to send messages back and forth to each other. So again, you might be profiling the "orchestration" process rather than the test assembly process itself.

You might be having more luck with xunit if it happens to be doing more "in-process" behavior at these pivotal moments.

**Comment by StevenTCramer** [comment]
https://stackoverflow.com/questions/48811188/how-to-switch-process-in-visual-studio-diagnostic-tools-window

This is the problem.  I see 

![image](https://user-images.githubusercontent.com/357219/118605236-400bbb00-b7e0-11eb-8d55-bc301950ad35.png)

In the Processes Window I have 

![image](https://user-images.githubusercontent.com/357219/118605322-5580e500-b7e0-11eb-94e6-771d60f3b4c2.png)

But I don't know how to get the Diagnostic Tool Window to show the dotnet.exe code.  So I can profile Fixie and the test runner but not my actual code.

The stackoverflow answers above don't fix the issue.  

Yet the Xunit tests don't show the test host.
