### ISSUE TITLE
Attribute based parameters with inherited classes fail only when ran with R# test runner

### ISSUE THREAD

**Issue by jayotterbein** [fixie/fixie#261]
This requires a few things:
* R# test runner (in VS or Rider)
* Tests with parameters (I only verified with attribute based parameters as in my example)
* The parameterized tests exist on a class that is inherited

When running tests either with the command line or with the Visual Studio runner all tests pass. When running with Rider or the R# test runner the tests show a hand symbol with zero information at the forefront, though there is some logs when clicking "Warnings" in the output window:

`2021.08.25 11:13:07.902    WARN Cannot create element for VsTestTestRowTask 'JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask': Parent with id 'InheritedWithParametersTests.InheritedClassTests.Should_add_numbers_inherited' does not exist
2021.08.25 11:13:07.903    WARN Run: b2543d1c-fa22-4813-8472-104b504e5e9e - Cannot find element for task <JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask> with id <29b48da6-e0b3-419b-9949-c03e89b0bad8>
2021.08.25 11:13:07.903    WARN Run: b2543d1c-fa22-4813-8472-104b504e5e9e - Cannot find element for task <JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask> with id <29b48da6-e0b3-419b-9949-c03e89b0bad8>
2021.08.25 11:13:07.903    WARN Cannot create element for VsTestTestRowTask 'JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask': Parent with id 'InheritedWithParametersTests.InheritedClassTests.Should_add_numbers_inherited' does not exist
2021.08.25 11:13:07.903    WARN Run: b2543d1c-fa22-4813-8472-104b504e5e9e - Cannot find element for task <JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask> with id <1816f1a7-4462-46f5-a1b0-51837d3c1f54>
2021.08.25 11:13:07.903    WARN Run: b2543d1c-fa22-4813-8472-104b504e5e9e - Cannot find element for task <JetBrains.ReSharper.TestRunner.Adapters.VsTest.Tasks.VsTestTestRowTask> with id <1816f1a7-4462-46f5-a1b0-51837d3c1f54>
2021.08.25 11:13:07.934    WARN Element executor://fixie.testadapter/::InheritedWithParametersTests.InheritedClassTests.Should_add_numbers_inherited was left running after its run completion.
`

## Steps to Reproduce

I have attached a minimal repo for this: [InheritedWithParameters.zip](https://github.com/fixie/fixie/files/7048414/InheritedWithParameters.zip)

## R# Test Runner behavior

Here is what I see when running with R#
![image](https://user-images.githubusercontent.com/5973193/130828175-ef01c216-73ea-474a-a73c-b2ebed59f281.png)

## VS Test Runner behavior

![image](https://user-images.githubusercontent.com/5973193/130828294-741bf321-9e24-465e-a39c-2a80d8601a78.png)

**Comment by plioi** [comment]
At first look, this is probably a bug report for JetBrains' VsTest integration, but I won't close this until I can take a closer look to see what's in our control.

**Comment by plioi** [comment]
Sorry for the delay, but I took a closer look at this today. It does really look like a JetBrains issue with their own general-purpose VSTest runner, so unfortunately I'm closing this issue.

Background:

Both the Test Explorer and ReSharper runners interact with Fixie using the "VS Test" protocol, and Fixie's side of that is to pass messages like "test started, test failed, ..." into a MS-provided sink. Anything we throw into that sink gets picked up by the 3rd party runner for interpretation. All those messages refer to tests by their fully qualified name (full test method name with namespace). Both UIs then choose to twist that flat series of events into a tree by making reasonable interpretations of the fully qualified names.

Clues:

First notice how even the *passing* inherited test is presenting abnormally in the ReSharepr tree vs the child class tests. It's not doing the same dotted-name parsing into the tree of nodes. That doesn't seem to have been a showstopper on that test, because there was never a moment where ReSharper needed to hang a new child node off of it. ReSharper's choice is to just use that single node for the single result to save you a click, and it must be getting a little lucky in looking up that node to note the success accurately.

For the red aborted test, we have a combination of the test node presenting in the same abnormal way, *plus* ReSharper wants to find that node to *attach* one additional child node for each parameterized invocation. I suspect that since the test method node was set up in this unexpected way, ReSharper's subsequent attempt to lookup that node to append extra children fails, then they can't hang the results off of it, then it rightly complains that something seems wrong.

Their log appears to agree. Those guids aren't from Fixie, and must be for their internal tracking of the tree.

The final clue in the log is "...was left running after its run completion". We issue events to them at the start of execution of any test so that they have the opportunity to draw a spinner, and if they were interpreting the test results successfully then they'd know the execution completed as soon as a pass/fail message matched it by name. If they're failing to match the results to the mixed up tree nodes, they never have a chance to note that execution finished and can't stop the possible spinner, but once we signal that the whole run is done, it rightly complains that something seems wrong.
