### ISSUE TITLE
Issue with debugging test in JB Rider

### ISSUE THREAD

**Issue by djordjedjukic** [fixie/fixie#270]
## Steps to Reproduce

- Setup Fixie 3.2.0 as per the wiki instructions
- Run tests, everything is ok
- Try to debug one test

## Expected Behavior

Test should pass

## Actual Behavior

Got an exception:

`One or more errors occurred. (Method 'get_Writer' in type 'Microsoft.AspNetCore.TestHost.ResponseFeature' from assembly 'Microsoft.AspNetCore.TestHost, Version=5.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.)`

In my BaseTest class I am using:

`TestServer = SetupHost().GetTestServer();`

```
public IHost SetupHost()
        {
            return new HostBuilder()
                .ConfigureWebHost(webBuilder =>
                {
                    webBuilder.UseStartup<Digitalis.Startup>().UseSerilog();
                    webBuilder
                        .UseTestServer()
                        .UseSetting("Google:ClientId", "client_id")
                        .ConfigureTestServices(collection =>
                        {
                            collection.AddAuthentication(FakeJwtBearerDefaults.AuthenticationScheme).AddFakeJwtBearer();
                            collection.AddSingleton<IDocumentStore>(Store);
                            collection.AddTransient<IMailer>(sp => Mailer);
                        });
                })
                .StartAsync().Result;
        }
```

**Comment by ChristophWeigert** [comment]
Did you find a solution to this? I'm not using fixie but got the same error in a Integration test.

**Comment by plioi** [comment]
I have not. I'm curious of your specific experience in case that will isolate whether fixie needs to do anything different.

Which test framework are you using? Which version of Visual Studio?

Does this happen for all tests?

See https://stackoverflow.com/questions/39615981/system-typeloadexception-method-get-xxx-does-not-have-an-implementation - Is there a chance your projects are referencing a mix of versions of the same dependencies?

**Comment by plioi** [comment]
I was never able to repro this, but closing with some context:

* For the most part, the target framework of the Fixie.TestAdapter project (vstest integration, and therefore JetBrains Rider integration), is irrelevant. For most runs, this process kicks off the test assembly as a separate exe, and so the test project's own target framwork is what matters at runtime.
* However, for JetBrains Rider runs *in debug mode*, we're unable to call the MS-provided "attach to that other process please" hook, and instead have to fall back to running in-process.
* As of 3.2.0 that meant netcoreapp3.1. Unfortunate. For such an in-process run, we have to rely on the tricky AssemblyLoadContext concept and I guess I'm not surprised if that can lead to a hiccup: an in-fact netcoreapp3.1 process, trying to load a net5.0 assembly and call into it, using the virtually undocumented AssemblyLoadConcept... yikes.
* I just release 3.3.0, which cross targets Fixie.TestAdapter to supported frameworks netcoreapp3.1, net6.0, and net7.0. I think this improves the odds of things working even in the problematic case of Rider + Debug... still in-process but now in-process for assemblies of the same actual target framework.
* I omitted net5.0 since that's already woefullly out of support by MS.
* Absolute worst case, when Rider debugging doesn't work, the "eject button" will be to instruct Rider to just run the test project directly *as if it were a console app, becasue it truly is* and debug like you would for any console app.
* If Rider + Debug mode continues to be problematic, I may need to throw out the attempts at doing things in-process and come at debuggability from some other approach entirely.
