### ISSUE TITLE
Fixie sometimes fails parameterized tests with "chunkLength" error

### ISSUE THREAD

**Issue by el2iot2** [fixie/fixie#325]
I understand this is a bit vague, but I am hoping that an extra pair of eyes (that is familiar with this tool's architecture) could spot a reason in which the following failure(s) could start occurring.

## Steps to Reproduce

I am not certain how to reproduce this, as we cannot (as of yet) identify why this started happening, and it is a "flaky" behavior in that it seems to sometimes work (with different build agents under different use pressures?) Our use of Fixie for L1 tests in an Azure DevOps YAML pipeline has been pretty stable. 

While I am hopeful of a fix, I realize this is a "long shot". I am probably not able to provide enough detail to reproduce and identify the problem because: 
1. The "flaky" and "emerging" nature of the failures (They only recently started failing, and fail about 70% of the time)
2. The proprietary context in which it exhibits (I cannot share the full context/code of the issue)
3. The failure does not occur locally (where I could debug myself) but only in a YAML pipeline hosted in Azure DevOps. (All local runs succeed)
4. This may all be a function of the very specific kind of tests (DB/DataLayer L1s) and the custom execution implementation involved (that I am not at liberty to disclose)
5. This could simply be masking some internal error that, when reported up to fixie, does so in an unexpected way and breaks the reporting mechanism.

## Expected Behavior
Continued reliable execution of tests (that had worked fine up until some shift in code/nuget/version/agent/?).

## Actual Behavior

Parameterized tests all fail with the same Exception:

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'chunkLength')
```

and callstack:

```
System.ArgumentOutOfRangeException
at System.Text.StringBuilder.ToString()
at Fixie.Internal.ExecutionRecorder.Pass(Test test, String name)
at Fixie.Test.RunCore(Object instance, Object[] parameters)
at OurCustomExecutionImplementation...
```

Thanks for your time and consideration...I will continue to attempt small shifts on my side to see if I can force more context, but I am hoping that there may be a flash of insight that might help solve this.

**Comment by plioi** [comment]
Unfortunately you are likely facing Fixie v3's biggest flaw, one that will hopefully go away in v4 as a breaking change. Unfortunately, for reasons I get at in #262 I won't be entertaining PRs for it, and won't be getting specific about time frame: I don't mean to be rude, just realistic.

What I write below, then, is about giving you some context in the hopes it lets you better troubleshoot what all might have changed recently to provoke Fixie's preexisting flaw, and to hopefully work around it.

This likely is not about parameterization, but instead about the consequences of the way Fixie attempts to capture the console's standard-out stream in the presence of multiple threads.

In an attempt to capture console writes that occur during test runs, the original "real" standard output `TextWriter` is wrapped very early in Fixie's execution, so that when your test or the system under test writes to `System.Console.Out`, we get an opportunity to *also* accumulate that text into a hidden StringWriter for inclusion in the per-test-result reporting. Usually this works out just fine, since the Fixie test runner itself is single-threaded, the default convention and all example custom conventions in the docs are single threaded, and the careful "mutable state juggling" we do as we move from one test to another *seemed* to be safely written in terms of a single apparent thread.

If you recently changed your custom `IExecution` to itself kick off multiple threads, such as attempting to run two tests at the same time, then that is unfortunately not supported in v3 for multiple reasons including this console capture problem.

For the rest of this comment, I'll assume your `IExecution` itself is not "doing thread things" itself directly.

Then the most likely thing that is going on is that some other thread is writing to `System.Standard.Out` at an unfortunately inconvenient time. Your stack trace strongly suggests this. Fixie's convinced it's a safe moment to take the underlying `StringBuilder` and call `ToString()` on it, but in fact some other thread is writing to `System.Standard.Out` around the same time, which in turn is getting appended into the underlying `StringBuilder`, and `StringBuilder` naturally isn't able to safely manage its own private state being hit like that from multiple threads.

There's a chance your test code is writing explicitly from some background thread it kicked off, or else your system under test is doing that, or else something more sneaky is going on. The first time someone reported this to me, in their case they started encountering the problem whenever they opted into some Entity Framework logging feature... presumably EF was offloading some of its own logging feature to a secondary thread it had kicked off; perfectly reasonable but revealing of Fixie's own assumptions. I suppose any logging framework might be doing a similar offloading of standard output writes to another thread.

If the console writes are coming direclty from your test code, you might instead write to the `Console` property of the `TestEnvironment` that I pass to your `ITestProject`. This console property is the real original value of `System.Console.Out` without the flawed wrapper involved, and is in fact what I write to in all the reporting infrastructure when a report needs to really write something to the user-facing console they ran `dotnet fixie` from.

The only reason I even bothered to capture console output was that some reporting sinks like Azure DevOps and the VS Test Explorer UI allow such output to be reported per test case. If you don't care about witnessing that in reports, you might try to "hit this problem with a sledgehammer" by redirecting standard out (this time, *away* from my flawed wrapper) very early in your `IExecution.Run(...)` method:

```cs
using TextWriter throwAwayConsole = new StringWriter();
System.Console.SetOut(throwAwayConsole);
// Reports won't show anything useful for the console output of individual
// test results, but at least we get the bug out of the way.
```

It would be even better, though, to take the `TestEnvironment` passed to your `ITestProject`, pass it into your `IExecution`, and then in `IExecution.Run(...)` do the following:

```cs
System.Console.SetOut(environment.Console);
// Again reports won't show console capture per-test-result, but at least all console output will actually go
// to the console, and could for instance appear in a CI log where you see `dotnet fixie` being invoked.
```

I hope this helps!

**Comment by el2iot2** [comment]
Indeed, it does help. And no worries about being frank on timeline/etc. I am a huge fan of this project, and the work you have done is excellent...It has already allowed me to build out some very interesting automated testing scenarios, and I am grateful for the project and the work you have already poured into it.

The thing you said about sneaky / opt in logging...especially around EF Core may well be the clue I needed. One of the moving pieces on our side was a move to EFCore 7.0, which may indeed have shifted what gets logged and how.

Your description of what you are doing to capture output and the perils involved helps me look into what sort of thing could be destabilizing. Thanks for your time and consideration. It is much appreciated.

I am closing this. Not only is your response an actionable hint, but also this is probably more a question/guidance inquiry than a "bug". I would have labeled it as such if I could have figured out how to do so. 

Regards,
Elliott
