### ISSUE TITLE
Consistent indentation settings

### ISSUE THREAD

**Issue by JonasSamuelsson** [fixie/fixie#41]
Use [EditorConfig extension] (http://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) so that all contributors has the same indentation settings.

**Comment by plioi** [comment]
Since the majority of Fixie's contributions come from folks who don't use the EditorConfig extension, and since whitespace inconsistency hasn't been a problem to date with people's pull requests, I'm going to close this issue and leave whitespace consistency as a responsibility of anyone who reviews a PR.
