### ISSUE TITLE
Add integration points

### ISSUE THREAD

**Issue by JonasSamuelsson** [fixie/fixie#45]
I would like to get your thoughts on some possible integration points for fixie.

I've put together a small proof of concept for a automated test runner for fixie (https://github.com/JonasSamuelsson/fixie.AutoRun), you select a visual studio solution, the application then monitors the file system for changes and complies and runs the tests.
![image](https://f.cloud.github.com/assets/2103937/2379801/0cb4b056-a8a0-11e3-8ddd-5f5e0ef54aa2.png)
![image](https://f.cloud.github.com/assets/2103937/2379861/a5e7baf2-a8a0-11e3-842f-27eb74e15c26.png)

There I needed to interact with fixie which turned out to be more difficult than I think it should.

Rigth now I'm redirecting the output from the ConsoleListener in order to know which test failed/passed but what I would like to do is;
- create a named pipe wcf endpoint in my application (with a random uri so I can have multiple instances running in the same time)
- provide my own listener implementation (that knows the addresss to my callback endpoint) to fixe
- when a test is executed the listener calls back in to my application with the result.

Aside from this I have identified a couple of concepts that would like to see in fixie
### Listener

Add a cases discovered method
Provide custom listener implementations
#### Implementation

``` csharp
interface Listener
{
    // existing methods
    void CasesDiscovered(IEnumerable<Case> cases)
}
```
#### Usage

```
fixie.console.exe -listener <assembly-qualified-name> [args...]
```
### Convention

Specify which convention to use. This way fixie could be used to execute tests build with any test framework without modifying the test assembly.
Conventions could be provided out of the box or developed by the community.
#### Usage

```
fixie.console.exe test-assembly.dll -convention:nunit
fixie.console.exe test-assembly.dll -convention <assembly-qualified-name> [args...]
```
### TestMethodFilter

Fixie.Runner currently have a set of methods to filter out test methods (RunAssembly, RunNamespace, RunMethod) but this should be extracted to an interface so you can combine filters and build your own.
There could be some out of the box filters available in fixie
#### Implementation

``` csharp
interface TestMethodFilter
{
    bool IsMatch(TestMethod method);
}

class TestMethod
{
    public TestMethod(MethodInfo methodInfo, IEnumerable<Tag> tags)
    {
        Method = method;
        Tags = tags;
    }

    public MethodInfo Method { get; private set; }
    public IEnumerable<Tag> Tags { get; privte set; }
}
```
#### Usage

```
fixie.console.exe test-assembly.dll -filter:namespace App.Some.Namespace
fixie.console.exe test-assembly.dll -filter <assembly-qualified-name> [args...]
```
### CaseComparer

This way it would be able to change the test execution order without modifying the actual convention
It would then be easy to support a scenario like http://ayende.com/blog/165922/tweaking-xunit
#### Implementation

``` csharp
implements IComparer<Case>
```
#### Usage

```
fixie.console.exe test-assembly.dll -comparer <assembly-qualified-name> [args...]
```
### Report

Makes it possible to generate custom reports
#### Implementation

``` csharp
interface Report
{
    void GenerateReport(ExecutionResult result);
}
```
#### Usage

```
fixie.console.exe test-assembly.dll -report:nunit nunit-report.xml
fixie.console.exe test-assembly.dll -report <assembly-qualified-name> [args...]
```

**Comment by plioi** [comment]
The Fixie 2.0 model is quite different.  Communication with 3rd party tools happens over a named pipe interprocess communication protocol.

1. It now provides test method discovery events, similar to your CasesDiscovered proposal.
2. We thoroughly regretted supporting more than one convention in a test assembly, both in the complexity it introduced in people's test projects and in the complexity of Fixie's implementation, so that is no longer supported. (If someone really, really wanted two different styles of tests, they can still accomplish that end result with a single convention that has a little more conditional logic in it). So your proposed --convention argument no longer applies as a built-in. Someone might use a custom command line argument, though, to affect their convention's discovery and execution behavior.
3. I plan to revisit the idea of a --filter argument similar to Jest, but I want some upcoming ReSharper work to help inform the requirements.
4. The sorting example you link to could still be done by a convention. The real meat of the custom work would be on the storing/loading of past durations.  I've added #184 as a prerequisite though.  Note that no matter what, each class needs to run as a single unit. The best one could do is sort by worst offending class, and then within that class sort by worst offending method.
