### ISSUE TITLE
Capture stdout and stderr when constructing test classes

### ISSUE THREAD

**Issue by JohnStov** [fixie/fixie#47]
ExecutionPlan.Execute() wraps all test methods run in a RedirectedConsole object, which ensures that all text output is captured.  The ReSharper runner depends on this feature.

Unfortunately, in both the CreateInstancePerTestClass ClassBehaviour and the CreateInstancePerCase ClassBehaviour, the construction of the test class is not captured by a RedirectedConsole, so any output is lost.  I suspect this is not obvious in a console runner, because the output will probably got to the console anyway.

For CreateInstancePerCase, it would make sense to prepend any console output generated in the contructor to the Output property in the FailResult or PassResult.  For CreateInstancePerTestClass, the solution is less obvious. It shouldn't be thrown away, though, which is what happens now.

**Comment by plioi** [comment]
Closing this due to age and due to the improved console capture just released in version 3.

The customization API is dramatically different than when this issue was first opened, and our handling of console capture is more reasonable in version 3.

Do note, however, that depending on how far outside the happy path one goes with their convention, there will likely always be some "gaps" in a custom lifecycle where console output will not arrive in Test Explorer while it would still arrive in a plain console run. Many improvements help around things like test class constructors, but there's still room for ambiguity on which test deserves which bit of console output beyond that emitted by the test method itself.
