### ISSUE TITLE
resharper plugin

### ISSUE THREAD

**Issue by JonasSamuelsson** [fixie/fixie#7]
In the comments to issue #5 you mention a resharper plugin, is this something you are working on, have on the todo list or "might do it but there is a ton of other stuff to do first"?

**Comment by pwhe23** [comment]
Fixie is a great project, but not being able to use the Resharper 9 test runner is the only thing holding our team back. I don't think I can convince them all to install TestDriven.net since we're so used to the Resharper test runner (using xUnit right now). I'm not sure if the JohnStov/ReSharperFixieRunner project is still active since there aren't any comments on recent issues. I wish I had time to dig into adding Resharper 9 support myself, but not at the moment.

**Comment by plioi** [comment]
@pwhe23 Thanks a lot for the feedback.

First, for what it's worth, the built-in support for the VS Test Explorer runner is 100% supported.  You get a visual runner, with MS's Test Explorer quirks.  The biggest thing you lose vs R# is that instead of a tree, you get a flat list.  However, if most of your tests are mostly passing, R#'s tree doesn't really offer much,.

Second, I really do want a R# runner that is equally supported.  At the moment, the one you find out there won't work.  The API changed a fair amount by Fixie 1.0's release.  Also, the R# API is surprisingly antagonistic to people wanting to make a test runner of their own, so it's quite a challenge to make.

Third, Microsoft's "vnext" suite of updates are surprisingly disastrous to all the .NET test frameworks.  xUnit has been the quickest to adapt, though, so we know it's possible and we have a model to follow.  The biggest obstacle, though, will require that we make a pretty significant breaking change to the API that we'd expose to a third-party runner like R#.  So, racing to get the R# runner up to date right now would likely be a wasted effort; best to wait until FIxie runs the vnext style of projects first.
