### ISSUE TITLE
Allow discovering non-public methods

### ISSUE THREAD

**Issue by TheCloudlessSky** [fixie/fixie#83]
Right now, [`MethodDiscoverer` does not allow discovering non-public instance methods](https://github.com/fixie/fixie/blob/cbe0c60eea34c2e87d82c410722aecbafb5f134c/src/Fixie/Internal/MethodDiscoverer.cs#L21). With xUnit.net, we have a lot of tests defined as:

```csharp
[Fact]
void FooBar()
{
    // ...
}
```

Is there any way we could maybe have a boolean option on `Configuration` like `AllowNonPublicMethods` which would be `false` by default:

```csharp
public IReadOnlyList<MethodInfo> TestMethods(Type testClass)
{
    try
    {
        var flags = BindingFlags.Public | BindingFlags.Instance;
        if (config.AllowNonPublicMethods)
        {
            flags |= BindingFlags.NonPublic;
        }
        var methods = testClass.GetMethods(flags).Where(IsMatch).ToArray();
    }
    // ...
}
```

Or, remove the `Public` flag all together (and change the `DefaultConvention` to ignore private methods)?

**Comment by ChrisMissal** [comment]
I believe you can just add this to your convention:

```csharp
Methods.Where(mi => !mi.IsPublic);
```

Warning: I haven't actually tested this. :)

**Comment by TheCloudlessSky** [comment]
No, that doesn't work because [the `MethodDiscoverer` filters the list of methods before the conditions are executed](https://github.com/fixie/fixie/blob/cbe0c60eea34c2e87d82c410722aecbafb5f134c/src/Fixie/Internal/MethodDiscoverer.cs#L21)

**Comment by ChrisMissal** [comment]
Oh, I see, I didn't look at the current implementation close enough.

**Comment by plioi** [comment]
The way the Reflection API works made it extra tricky to support the condition as Chris suggested.  But, that decision was made a long time ago, and with fresh eyes it's worth looking at this again.  My main concern would be to avoid surprising people who *don't* expect private methods to be considered.  As soon as someone moves away from using attributes as their rule of thumb, you'd run into ambiguity: "is this a test method, or a private helper method used by my tests?"  As long as the default is public only, though, I might include such a feature.

**Comment by TheCloudlessSky** [comment]
Ok, great. Would you envision this as a property on `Convention` (`MethodBindingFlags` or `AllowNonPublicMethods`)? I definitely don't mind making a PR for this.

**Comment by plioi** [comment]
Before making a PR, I'd want to weigh the risks vs the reward some more.  Being able to fully mimic the other test frameworks isn't a paramount goal.  Is the benefit brevity?  What about when you've got a private method that you don't want to be a test?

**Comment by ChrisMissal** [comment]
Other than the time it would take, are there other challenges you're up against by changing them to public @TheCloudlessSky ?

**Comment by TheCloudlessSky** [comment]
It's easy to make them public. So, yes, the main advantage is brevity. You're right about having a private method (and not wanting to test it). You can also note that we've explicitly decorated these methods as `[Fact]` (which is the same as typing `public`).

But, one idea that we've been playing around with is reducing the ceremony for our tests to conventionally have something like:

```csharp
void it_sends_a_notification_to_all_members()
{
    // ...
}
```

Which is similar to Machine.Specifications (except we're not using a field). Or:

```csharp
void ShouldSendANotificationToAllMembers()
{
    // ...
}
```

We'd conventionally look for all methods with `it_` prefix or `Should` prefix.

**Comment by plioi** [comment]
I've outlined Fixie's Road Map on the [wiki](https://github.com/fixie/fixie/wiki), including the factors that affect whether or not we'll adopt a given feature, in order to help me make decisions about our open Issues and Pull Requests. Unfortunately, I need to close this feature request in light of the following two points listed there:

> * Does the feature encourage end users to use idiomatic C#?
> * Does it push people toward the pit of success, or does it instead lead them into making easy mistakes?

Having a framework call directly into private methods is possible, but not iodiomatic C#. Consider the analogy with controller actions in ASP.NET MVC. If private methods in controllers could be hit by incoming web requests, people would be very likely to be surprised by that subtlety. So goes with tests, in which test classes often have a private helper method or two.

Sure, in combination with an xUnit-like \[Fact\] attribute one can avoid ambiguity, but for any end user that didn't realize the need for such a thing, they could easily fall into the trap of writing helper methods that get mistakenly executed as tests. It's just too likely to cause trouble for folks.
