### ISSUE TITLE
Provide a way to filter tests in test runners (and possibly Test Explorers)

### ISSUE THREAD

**Issue by Gilligan128** [fixie/fixie#92]
It would be great to have a way to filter tests in various runners, like the vs runner or the Resharper runner or the Test Explorer in VS. 

Current solutions I see in testing frameworks is to have a Trait concept identified by a string value. This seems a pretty good solution. The question is how would one implement Traits in Fixie (tbh I also like the the term "Tags").

The simplest thing I can think of is to have a separate "Convention stream", alongside Methods, CaseExecution, etc. but I am not very familiar with the codebase yet so this is a best guess.

I also don't know how all the different test runners determine "traits" or if they can even support them, so this is sort of a question mark in my mind. I am investigating.

**Comment by Gilligan128** [comment]
From my research, it looks like Traits are explicitly used when discovering tests, but not when running them. I think a "minimum viable" version of this feature could be some Options convention, like "if there is an 'include' value then use that for Trait discovery" and then for running the tests, just use method prescribed in documentation for the console runner.

**Comment by plioi** [comment]
That sounds similar to my NUnit Categories sample convention, which allows for filtering when run from the console runner: https://github.com/fixie/fixie/tree/master/src/Fixie.Samples/Categories

Does TFS actually use the VS runner? An odd choice by MS if it does.

**Comment by Gilligan128** [comment]
I should clarify: We are using the TFS Build Server (I don't like it but there you have it). That Build Server I am pretty sure is uing the VS Runner. I could shell out the test running to our powershell scripts (I do for the Acceptance tests) but then then our error messaging is  a bit convoluted. Additionally, there is still the issue that we cannot choose "categories" of tests to run in the Test Explorer, even when using the Fixie Runner, because there is no way for the Test Discoverer to pass in what tests to filter atm.

**Comment by plioi** [comment]
Understood. Thanks for clarifying!

**Comment by plioi** [comment]
Today, I've studied the implementation details of the NUnit VS Test Adapter, because it does take part in the traits infrastructure both for Test Explorer and TFS Build filtering.

My main focus was on the use of the VS-provided types from the Microsoft.VisualStudio.TestPlatform.ObjectModel namespace.

I don't declare defeat yet, but there's a definite "impedance mismatch" between the concepts VS wishes test runners had ("Hey everybody, be more like MSTest!") and the concepts the target test framework actually has.

Before I start laying out several possible plans of attack, I'd like some more input on the TFS Build use case.  When you configure things for NUnit, what does that look like?  Apparently there is a special string format for specifying what you want to run, a complex example being:

    (TestCategory!=UI&(Priority=1|Priority=2))|(TestCategory=UI&Priority=1)

Some of what makes this tricky is that the part of all this that's baked into Visual Studio has a few strongly held opinions that are true for MSTest and absolutely false elsewhere.  For instance, at discovery time, Fixie deliberately only reports *method groups* as test cases instead of each test case that will actually exist at execution time (this applies to overloaded tests and more importantly to parameterized tests).  If I strayed from this focus on method groups, you get a horribly glitchy experience in the UI that you can experience with NUnit and I don't want to introduce for Fixie.  But, then that makes traits-per-test-case technically impossible.

Again, I don't give up, but the short version is that TFS Build and Visual Studio make some quite-false assumptions about how a test framework is going to work, and there might not actually be a good compromise here.  I'll keep researching.

**Comment by Gilligan128** [comment]
hmm. Thanks for that insight. We use mstest right now as our test framework, not mstest. I will post what the filtering looks like tomorrow, but it has to do with adding TestCategoryAttributes("string") and then specifying these attributes with bitwise and/or operations. 
Ok I may have a limited understanding of method groups, but, I would imagine you would have a Trait per Method Group, not Test Case. Although I could see enforcing this for method overloads may be tricky.  
I hope that added info helps. And also, for my particular case, I think I could convince the devs to sue a diff runner for running tests locally and then just shell out the ci tests. I hate TFS CI anyway. But the real question is whether there is a demographic of ppl stuck with such technology that may want to use Fixie? 
Honest to God, I think Fixie may explode to the point where people will be like "Remember when we used Test FRAMEWORKS?" but the Msoft world is really hit or miss with this stuff.

**Comment by Gilligan128** [comment]
I don't see a huge problem disallowing the traits-per-test-case situation and just Traiting by Method Group e.g. "Traits.Select(methodGroup => new Trait[] {'fast'})" or something like that. Usually Traits are used for filtering and I cannot imagine a use case where someone would not want all overloads on a method to be the same Trait. If they do, well then that is their problem.

**Comment by Gilligan128** [comment]
Is there anything I can help with this?

**Comment by plioi** [comment]
Apologies for the delay. I've got a project at work wrapping up this week, so I haven't had quite enough time to look into this until now.  I would be *greatly* appreciative of your help, if you're still interested.

Regarding my concerns about `MethodGroup`, I think this new feature request is really telling me that *I* just plain got it a little wrong when I first implemented the VS runner, oversimplifying things.  I have a plan ready to take the opportunity to fix that as a part of making this feature work.

You'll see that I've created a new branch with no work on it yet, called "traits".  Please make sure that any PR for the traits feature is against that branch, so we can keep master open to things like urgent bug fixes.  I think this traits feature will be best handled as a series of smaller PRs against the traits branch, instead of all-at-once.  I want to break it into multiple PRs because:

1. It makes it a lot easier to review each piece. The previous attempt at traits had a *lot* going for it, but it was such a large PR that I had trouble bringing it in at a time when the rest of the infrastructure was still in flux.  I wasted that other developer's time and effort as a result, and I want to avoid similar trouble this time.
2. There are a few pieces of the overall feature I might be able to implement at the same time you're working on other parts.
3. My plan for the multiple PRs is probably wrong in some way I won't see until we're partway through it, and I don't want to waste your time handing you a very large but flawed design to implement :)

If you're still interested in helping, I'd like to see a first PR that does all of the following:

First, a new class, `Trait`, with read-only string properties `Name` and `Value`.

Next, the ability to define where traits come from in a convention, even though they definitely won't be very usable for anything until later Pull Requests.  The existing convention API support for parameterized cases will be our best model of how to implement this part.  Here's the goal, a snippet that we can place inside a custom convention:

```cs
Traits
    .Add<MyTraitSource>() //specify a type name that knows how to find traits
    .Add(new MyTraitSource()) //specify an instance of such a type
    .Add(methodInfo => enumerable of Trait) //specify a func that is equivalent to such a type
```

To accomplish this API, we'll need a `TraitSource` and `TraitSourceFunc` similar to `ParameterSource` and `ParameterSourceFunc`.  This time, though, we need the operations to be `MethodInfo => IEnumerable<Trait>`. See `ParameterSourceExpression` for how to create these 3 "Add" overloads, resulting in a new `TraitSourceExpression`. Armed with `TraitSourceExpression`, `Convention` can gain the `Traits` property from the above snippet.

If an end user can successfully define conventions in this way, even though they don't *yet* have any *effect*, I'll accept the PR.  There's probably very little of this that can be tested; we'll make sure we have good coverage in the followup PR that makes them more useful. We can talk about next steps once this first PR is in.

**Comment by Gilligan128** [comment]
I agree small PRs is a great way to go. If I may sugest an alternative approach to breaking them down, however. We could go in a more "Minimum Viable Product" direction, where I can start with as simple a Trait as possible and implement it through the entire system. THis way we can get testing right away while still keeping the PR small, following the "Convention" conventions, and refactoring into more complex Traits.

Example: We could create only one Trait that either be turned off or on that will create a new Trait from the first letter of the test's class name. We can then test that the tests are grouped by this trait. 

Here is a potential PR order:
1) one Trait for the first letter of the Method Gorup name that is always there.
2) The ability to turn off and on that Trait.
3) The ability to decide whether to use the first letter or the last letter of the Method Group name.
4) At this point, perhaps we can implement full-blown customization based on your guidelines.

What do you think of doing it this way? I will start implementing this stuff either way, however, due to an upcoming conference at which I am presenting I am not sure how far I will make it. I at least want to get the first PR out in the next week or two.

**Comment by Gilligan128** [comment]
OK, this might be a silly quesion, but how are you running the tests in the codebase? You using the console runner?

**Comment by plioi** [comment]
At the command line, running just "build" will compile and run all the tests.  Inside VS, I run them with TD.NET.  Due to the lame way that VS detects and installs runners found in nuget packages, I can't actually use the VS Fixie runner to run Fixie's own tests.

**Comment by plioi** [comment]
Closing due to age, interest, and the upcoming deprecation of VSTest.

VSTest is being deprecated by the new `Microsoft.Testing.Platform` which will form the primary focus for v5. https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro

Capabilities of the new platform are a work in progress on the MS side and will influence anything we do here on this side.
