### ISSUE TITLE
Question: Should the console runner be in tools?

### ISSUE THREAD

**Issue by wallymathieu** [fixie/fixie#94]
Many of the testrunners for other projects are in the tools folder. As far as I understand, the files in the lib folder is supposed to be referenced by the project?

**Comment by plioi** [comment]
I'm especially unsure of this now that I've been playing with VS2015 this week.  VS2015 and the latest version of NuGet have serious breaking changes so that this kind of "solution-level" content isn't handled well anymore, if at all.  They may be considering fixing that since it's so destructive to things like build tools and database migration tools.  In the meantime, I'm leaving things as-is while the dust settles.

**Comment by wallymathieu** [comment]
They (on the nuget blog) mentioned that post install scripts are getting deprecated. Solution level packages does not affect the format of nuget format : https://docs.nuget.org/Create/Creating-and-Publishing-a-Package
You can still have tools. It's just that the thinking is that you install them in a project:
http://blog.nuget.org/20151008/NuGet-3-What-and-Why.html
